# Generated by Django 2.2.4 on 2019-08-27 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('Admin', 'Admin'), ('AppStaff', 'AppStaff'), ('OutsideRep', 'Rep')], default='OutsideRep', max_length=50, verbose_name='Set Access Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Access Level')),
            ],
        ),
    ]
