# Generated by Django 2.2.4 on 2019-09-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190829_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessLevel',
        ),
    ]
