# Generated by Django 2.2.4 on 2019-09-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CorpInfo',
            new_name='OwnerInfo',
        ),
    ]
