# Generated by Django 2.2.4 on 2019-08-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpInfo',
            fields=[
                ('corp_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('personal_email', models.EmailField(max_length=255)),
                ('corp_email', models.EmailField(max_length=255)),
                ('phone_1', models.CharField(max_length=20, verbose_name='ex. 123-123-4567')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='ex. 123-123-4567')),
                ('home_address', models.CharField(max_length=255)),
                ('old_home_address', models.CharField(blank=True, max_length=255)),
                ('ssn', models.CharField(max_length=9)),
                ('corp_name', models.CharField(max_length=255)),
                ('second_corp', models.CharField(blank=True, max_length=255)),
                ('referral', models.URLField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('contact_type', models.CharField(choices=[('On boarding', 'On boarding'), ('Active', 'Active Paid'), ('Former', 'Former')], max_length=255)),
                ('account_manager', models.CharField(choices=[('Thomas', 'Thomas'), ('Patrick', 'Patrick')], max_length=255)),
                ('gdrive', models.URLField()),
                ('payments', models.IntegerField(default=0)),
            ],
        ),
    ]
