# Generated by Django 2.2.4 on 2019-09-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_auto_20190902_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerinfo',
            old_name='corp_id',
            new_name='owner_id',
        ),
    ]
