# Generated by Django 2.2.4 on 2019-09-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_auto_20190902_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerinfo',
            name='old_home_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Previous Address'),
        ),
        migrations.AlterField(
            model_name='ownerinfo',
            name='payments',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='ownerinfo',
            name='phone_1',
            field=models.CharField(max_length=20, verbose_name='Phone ex. 123-123-4567'),
        ),
        migrations.AlterField(
            model_name='ownerinfo',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alt Phone ex. 123-123-4567'),
        ),
    ]
