# Generated by Django 2.2.5 on 2019-09-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_auto_20190903_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerinfo',
            name='payments',
            field=models.IntegerField(default=0),
        ),
    ]
