# Generated by Django 2.2.5 on 2019-10-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0005_auto_20190925_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectiveOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('personal_email', models.EmailField(max_length=255)),
                ('phone_1', models.CharField(max_length=20, verbose_name='Phone ex. 123-123-4567')),
                ('home_address', models.CharField(max_length=255)),
                ('contact_date', models.DateField()),
                ('referred_by', models.CharField(max_length=255)),
                ('notes', models.TextField()),
            ],
        ),
    ]
