# Generated by Django 2.2.4 on 2019-08-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accesslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_appstaff',
            field=models.BooleanField(default=False, verbose_name='AppStaff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_rep',
            field=models.BooleanField(default=False, verbose_name='OutsideRep'),
        ),
        migrations.DeleteModel(
            name='AccessLevel',
        ),
    ]
